name: "Build action: Foxy, Galactic, Rolling"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-20.04, windows-latest, macOS-latest ]
        os: [ ubuntu-20.04 ]
        ros_distribution: [ foxy, galactic, rolling ]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@v0.2
      with:
        package-name: fmi_adapter
        vcs-repo-file-url: dependencies.repos
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
